### PR TITLE
Fix product to work on Plone5 in production

### LINKED ISSUE #46: Javascript doesn't work in production for Plone 5
This is an issue after version 2.0.

### PR DESCRIPTION
**Pull request by djowett-ftw**
Resolves #46 

    Also Fix on click event for edit form tabs

    - Rework JS for Plone5
    - Move Plone's Select2 aside while running JS for this product
    - Add select2 v4.0 into our bundle without inlining it in our source
      Note: we ensure correct ordering of the select2 libraries by using 'depends' on the bundle rather than 'require' in JS
    - Rebuild with plone-compile-resources (added to test-plone-5.1 buildout)

~This doesn't yet use the @buchi method (with yarn) for the JS compilation. That's on the way.~

### CODE REVIEW

**Comment by djowett-ftw** [comment]
:-( Oh - seems to still not work with bundles in production

**Comment by djowett-ftw** [comment]
This now uses yarn and works in a production setup (contrary to the notes above)

**Comment by djowett-ftw** [comment]
@maethu quick question - while working on this I notice that the SCSS file is ahead of the CSS file, but there seems to be no generation of the latter from the former.  How should this worK?

**Comment by maethu** [comment]
@djowett-ftw I kinda don't understand the question. We usually use scss and not css anymore. With ftw.theming wit use mostly scss.

**Pull request merged**
